import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-merchant-acquiring-interchange-fee-recovery",
  "engine": "recovery",
  "title": "Merchant Acquiring & Interchange Fee Recovery",
  "shortTitle": "Merchant Fee Recovery",
  "tagline": "Reconstruct card acceptance costs and recover processor, network, and interchange leakage",
  "industry": "Merchant Payments Cost Recovery",
  "uiPort": 4571,
  "apiPort": 5571,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Card acceptance fees independently recalculated and unsupported costs converted into processor credits",
  "valueNarrative": "Turn processor agreements, transaction details, interchange qualification, network assessments, statements, and credits into measurable payment-cost recovery.",
  "calculation": {
    "actualKey": "chargedFees",
    "expectedKey": "supportedFees",
    "actualLabel": "Processor Charged Fees",
    "expectedLabel": "Contract-Supported Fees",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Transaction qualification, network, and processor contract evidence indicate unsupported card-acceptance fees.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("processor-agreement-library","MFR01","Processor agreement library","Reconcile processor agreement library using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed processor agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Processor agreement library Reference","text","MFR01-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("merchant-account-registry","MFR02","Merchant account registry","Reconcile merchant account registry using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed merchant account registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Merchant account registry Reference","text","MFR02-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("card-transaction-ingestion","MFR03","Card transaction ingestion","Reconcile card transaction ingestion using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed card transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Card transaction ingestion Reference","text","MFR03-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("interchange-qualification-reconstruction","MFR04","Interchange qualification reconstruction","Reconcile interchange qualification reconstruction using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed interchange qualification reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Interchange qualification reconstruction Reference","text","MFR04-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("card-brand-assessment-validation","MFR05","Card-brand assessment validation","Reconcile card-brand assessment validation using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed card-brand assessment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Card-brand assessment validation Reference","text","MFR05-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("processor-markup-reconciliation","MFR06","Processor markup reconciliation","Reconcile processor markup reconciliation using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed processor markup reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Processor markup reconciliation Reference","text","MFR06-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("downgrade-detection","MFR07","Downgrade detection","Reconcile downgrade detection using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed downgrade detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Downgrade detection Reference","text","MFR07-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("duplicate-fee-detection","MFR08","Duplicate fee detection","Reconcile duplicate fee detection using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed duplicate fee detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Duplicate fee detection Reference","text","MFR08-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("refund-and-reversal-fee-audit","MFR09","Refund and reversal fee audit","Reconcile refund and reversal fee audit using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed refund and reversal fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Refund and reversal fee audit Reference","text","MFR09-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("cross-border-and-currency-fee-audit","MFR10","Cross-border and currency fee audit","Reconcile cross-border and currency fee audit using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed cross-border and currency fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Cross-border and currency fee audit Reference","text","MFR10-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("tokenization-qualification-analysis","MFR11","Tokenization qualification analysis","Reconcile tokenization qualification analysis using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed tokenization qualification analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Tokenization qualification analysis Reference","text","MFR11-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("chargeback-fee-reconciliation","MFR12","Chargeback fee reconciliation","Reconcile chargeback fee reconciliation using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed chargeback fee reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Chargeback fee reconciliation Reference","text","MFR12-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("monthly-statement-audit","MFR13","Monthly statement audit","Reconcile monthly statement audit using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed monthly statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Monthly statement audit Reference","text","MFR13-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("processor-dispute-package","MFR14","Processor dispute package","Reconcile processor dispute package using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed processor dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Processor dispute package Reference","text","MFR14-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("recovered-fee-ledger","MFR15","Recovered fee ledger","Reconcile recovered fee ledger using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed recovered fee ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Recovered fee ledger Reference","text","MFR15-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]}),
feature("processor-channel-and-location-analytics","MFR16","Processor channel and location analytics","Reconcile processor channel and location analytics using processor agreements, card transaction detail, interchange qualification, network assessments, settlement statements, refunds, and credits.","Produce a governed processor channel and location analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["processorMerchant","Processor / Merchant Account","text","Apex Payments / MID-884120"],["caseReference","Processor channel and location analytics Reference","text","MFR16-2026-001"],["chargedFees","Processor Charged Fees","currency",428000],["supportedFees","Contract-Supported Fees","currency",361500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Omnichannel retailer","Restaurant group","Healthcare network","Subscription merchant","Marketplace portfolio"]})
]);
